### ISSUE TITLE
mcs: same RV values aren't reused unless generate_trials! is called

### ISSUE THREAD

**Issue by ckingdon95** [anthofflab/Mimi.jl#313] opened 2018-09-05 15:18 UTC
If the user doesn't explicitly call the `generate_trials!` function, then different random variable values are generated for each trial set in each scenario, instead of reusing the same trial values.

Here's an example where the same values get reused in the case of calling generate_trials!, but different values get used when it's not called. Output shown below:

```
# Show reusing parameters bug

using Mimi
using Distributions

mcs_test = @defmcs begin
    n = Normal()
end 

@defcomp test begin
    n = Parameter(default = 0)
    function run_timestep(p, v, d, t) end
end

scenario_args = [
    :num => [1,2,3]
]

function scenario_func(mcs::MonteCarloSimulation, tup::Tuple)
    println("   Scenario $(tup[1])")
end

function post_trial_func(mcs::MonteCarloSimulation, trialnum::Int, ntimesteps::Int, tup::Tuple)
    m, = mcs.models
    println("       trial $trialnum: ", m[:test, :n])
end

m = Model()
set_dimension!(m, :time, 2000:2001)
add_comp!(m, test)
set_model!(mcs_test, m)

trials = 2

println("Without generating trials first:")
run_mcs(mcs_test, trials; 
        output_dir = "out",
        scenario_args = scenario_args,
        scenario_func = scenario_func, 
        post_trial_func = post_trial_func
        )
        
println("With generating trials:")
generate_trials!(mcs_test, trials; filename = "trials.csv", sampling=RANDOM)
run_mcs(mcs_test, trials; 
        output_dir = "out",
        scenario_args = scenario_args,
        scenario_func = scenario_func, 
        post_trial_func = post_trial_func
        )
```
prints the following (and saves output):

```
Without generating trials first:
   Scenario 1
       trial 1: -2.5829748183984096
       trial 2: 0.49678714554895137
   Scenario 2
       trial 1: -0.7339218179487421
       trial 2: 1.9628955942196258
   Scenario 3
       trial 1: -0.17198597396484852
       trial 2: -0.9781772107616433
With generating trials:
   Scenario 1
       trial 1: -0.6177686257667423
       trial 2: -0.8378265972914327
   Scenario 2
       trial 1: -0.6177686257667423
       trial 2: -0.8378265972914327
   Scenario 3
       trial 1: -0.6177686257667423
       trial 2: -0.8378265972914327
```

**Comment by ckingdon95** [comment] 2018-09-05 15:30
idea: do we need to create SampleStore's for each RV in rvdict during the first run if generate_trial! wasn't called?

**Comment by rjplevin** [comment] 2018-09-05 15:36
Maybe. There are some use cases here I hadn't anticipated (e.g., not calling generate_trials!). We might want to take a step back and enumerate the variants we want to support and ensure that each is handled correctly. The relationship between `SampleStore` and `EmpiricalDistribution` might also warrant re-thinking.

**Comment by rjplevin** [comment] 2018-09-05 16:02
Some thoughts... We have the following considerations:

- Sampling method: LHS vs random
- Pre-computed / empirical distributions (or loaded from file) vs on-the-fly calls to `rand!`
- Saving trial data: currently possible only if generated up front. On-the-fly values aren't saved.
- Reuse of RV values across scenarios: Currently `get_trial` maintains a 1-level cache to support this.
- Outer vs inner scenario loop: outer loop requires saving all trial data

I believe the bug you hit is an outer scenario loop with an `EmpiricalDistribution`, the draws for which aren't saved, so when `_reset_rvs!` is called, the `Normal` distribution (which becomes a `SampleStore`) is reused, but the `EmpiricalDistribution` just keeps calling `rand`.

**Comment by rjplevin** [comment] 2018-09-05 16:09
It looks like the cause of the error is this line in mcs_types.jl:
```
self.dist_rvs = [rv for rv in rvlist if rv.dist isa Distribution]
```
The `EmpiricalDistribution` is not a subtype of `Distribution`, so it's excluded from this vector and then not converted to a `SampleStore` along with the `Normal` distribution (in `function Base.rand!(mcs::MonteCarloSimulation)`) I'll need to remember why I did it this way...

**Comment by ckingdon95** [comment] 2018-09-05 17:00
That is the cause of the EmpricalDistribution error, but not of the error that without generate_trials, ALL types of distributions fail to reuse the same values across scenarios.

**Comment by rjplevin** [comment] 2018-09-05 18:32
Removed the restrictions (and created a PR). Now I get this:
```
new component Main.test
Scenario 1
   trial 1: normal=0.4969853542263138 cs=5.0
   trial 2: normal=-0.860577266684947 cs=3.0
   trial 3: normal=0.46312462994855286 cs=2.0
Scenario 2
   trial 1: normal=0.4969853542263138 cs=5.0
   trial 2: normal=-0.860577266684947 cs=3.0
   trial 3: normal=0.46312462994855286 cs=2.0
Scenario 3
   trial 1: normal=0.4969853542263138 cs=5.0
   trial 2: normal=-0.860577266684947 cs=3.0
   trial 3: normal=0.46312462994855286 cs=2.0
Scenario 4
   trial 1: normal=0.4969853542263138 cs=5.0
   trial 2: normal=-0.860577266684947 cs=3.0
   trial 3: normal=0.46312462994855286 cs=2.0
```

**Comment by rjplevin** [comment] 2018-09-05 18:33
(I changed trials from 2 to 3, too. ;~)

**Comment by rjplevin** [comment] 2018-09-10 16:20
Cora -- if you consider this resolved, would you close the issue? If not, let's figure out what's left to do.

**Comment by ckingdon95** [comment] 2018-09-10 17:39
@rich this issue isn't resolved, but the EmpiricalDistribution issue #312 is. (some of the comments you left here should have been on that thread I think)

**Comment by rjplevin** [comment] 2018-09-10 18:17
It's still not clear to me why calling `generate_trials!` is objectionable. This allows you to select the sampling method and to store trial data in a file. If we call this from within `run_mcs`, we'd need to add parameters for those options to pass them into `generate_trials!`.

I'd also want to leave the option of _not_ reusing values in the outer scenario loop. (This is relevant only for "outer" scenarios since "inner" scenario values are, by definition, varied within the MCS sampling loop). 

So we could add three optional parameter:
```
run_mcs(..., generate_trials::Bool=true, filename::String="", sampling::SamplingOptions=LHS)
```
and after `mcs.trials = length(trials)` add:
```
if generate_trials
  generate_trials!(mcs, mcs.trials, filename=filename, sampling=sampling)
end
```
I have a question about the semantics of the optional `generate_trials` argument: should this mean _always_ generate new trial data, or only if it hasn't been generated yet? If the latter, how does one force regeneration of trial data? (Could call `generate_trials!` before calling `run_mcs` of course.)

It seems simpler to me to just call `generate_trials!` explicitly rather than trying to figure out when to call it automatically without creating surprising behavior.

**Comment by ckingdon95** [comment] 2018-09-10 18:45
I was assuming we always wanted scenarios to reuse the same draws, and I didn't realize that we wanted the option of _not_ reusing values, which changes things. So it's just a question of what we think the default behavior should be. 

I think I can get on board then with requiring the call to `generate_trials!`, but there's a few things I'm still iffy about. I think this confusion for me is caught up in the dual purpose of the `generate_trials!` function then: it both allows the user to specify a sampling method as well as mandating the reuse of values. So what happens then if a user wants to specify a sampling method but _doesn't_ want to reuse values?

This is then related to issue #300, I think we should add the sampling option to the `run_mcs` function. (I think this would solve the problem of a user wanting to specify sampling but not wanting to reuse values?)

I would also propose that if you call `generate_trials!` without a filename argument, it still pre-generates the data, but doesn't save to a file. (currently if you don't give a filename it doesn't make SampleStores, at least in the RAND case)

note to self: these changes might require more error checking, for example:
- if a certain sampling method is called during generate_trials, and then a different one during run_mcs, how do we handle that
- if a user pre-generates data with generate_trials, but then does run_mcs with scenario_loop=INNER what happens

**Comment by ckingdon95** [comment] 2018-09-10 18:49
potential plan:
- Require a user to call `generate_trials!` if they want scenarios to use the same values
- Enable option of calling `generate_trials!` to reuse values without saving to a file
- add sampling option to `run_mcs` (so user can specify sampling without reusing values across scenarios)

If we do these things, this prevents the user from being able to save trial data if they don't want to reuse values across scenarios (which is currently also the case). What would be the best way to add this ability?

**Comment by ckingdon95** [comment] 2018-09-10 19:48
Agree to make changes: default to RANDOM, and remove filename check.

A couple remaining questions:

- LHS requires calling the samples up front, but that doesn't mean they have to be re-used across scenarios right? Do we want to support using LHS but with different values across scenarios? This doesn't seem necessary to me, but this would be a missing case. 
- If the user wants to have different trial data across scenarios, there is no way for them to save the trial data. (unless they do something fancy like call generate_trials in their scenario_func, which feels convoluted)
- RE your earlier concern of what happens if you call generate_trials! multiple times: do we want this to reset the SampleStore values? (I think this is what it currently does?)

**Comment by rjplevin** [comment] 2018-09-10 20:53
I don't see this as something we need to explicitly support. I think the case of drawing new values within the scenario loop makes sense for `RANDOM` than for `LHS` since the way the latter is stratified (values are drawn from 1/num_trials equal-probability segments and shuffled), you'd just get approximately the same set of values in a different order (at least for any reasonably large sample size). 

In the unlikely case that someone wants to do this, they could arrange the resampling / saving in their scenario func. But it strikes me as unlikely, so I'm ok ignoring this use case.

> RE your earlier concern of what happens if you call generate_trials! multiple times: do we want this to reset the SampleStore values? (I think this is what it currently does?)

I need to think about this. Calling `generate_trials!` a second time doesn't currently work if you've defined any correlations. I'm inclined to modify the MCS code to save the original distribution information so that on a subsequent call, the original is reused, rather than the `SampleStore`. This might be as simple as storing the `rvdist` in the `SampleStore` (allowing that it might be `nothing` for data loaded from a file.)

I'd be happy to work on this since you're reaching the end of your work day...

**Comment by ckingdon95** [comment] 2018-09-10 21:02
@rjplevin I just started PR #317  on the mcs-debug branch referenced above with the two simple changes we said. If you'd like to play around with the last few things you mentioned, feel free to push any changes to there! (I'm taking off for the day soon)

**Comment by ckingdon95** [comment] 2018-09-11 17:49
#318

**Closed** 2018-09-11 20:46 UTC
Labels: bug
