### ISSUE TITLE
Using Variables to set Time in @defmodel

### ISSUE THREAD

**Issue by lrennels** [anthofflab/Mimi.jl#278] opened 2018-07-27 19:45 UTC
This bug was found in fund, and the `@defmodel` macro in fund should be updated to include users to choose `ntimesteps` once it is fixed.

The following code produces the error `ERROR: UndefVarError: nsteps not defined`, however println(nsteps) works properly, showing that this bug is likely within the `setdimension!` call by the macro.

```
using Mimi

global const nsteps = 100

Mimi.@defmodel FUND begin 
    m = Model()
    index[time]     = collect(1950:1950+nsteps)
end
```

**Comment by rjplevin** [comment] 2018-07-27 20:00
The problem is that `nsteps` is out of scope when the code is evaluated in the macro. It should work if you specify it inside the macro as `FUND.nsteps` (assuming the `@defmodel` is in module `FUND`)

**Comment by lrennels** [comment] 2018-07-27 20:05
Ah ok I was missing the module part, thanks!

**Closed** 2018-07-27 20:06 UTC
Labels: bug
